services:
  grok2api:
    container_name: grok2api
    image: python:3.13-alpine
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache tzdata ca-certificates libffi openssl libgcc libstdc++ libcurl curl-dev build-base linux-headers libffi-dev openssl-dev cargo rust &&
        cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&
        /app/scripts/init_storage.sh &&
        pip install uv --quiet &&
        uv sync --frozen --no-dev --no-install-project &&
        uv run uvicorn main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "30015:8000"
    environment:
      TZ: Asia/Shanghai
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      LOG_LEVEL: INFO
      SERVER_PORT: 8000
      SERVER_WORKERS: 1
      SERVER_STORAGE_TYPE: local
      # SERVER_STORAGE_URL: 

      # SERVER_STORAGE_TYPE: (local, redis, mysql, pgsql) default: local
      # SERVER_STORAGE_URL: (local mode is empty) default: empty
      #   Redis: redis://localhost:6379/0 or redis://:password@localhost:6379/0
      #   MySQL: mysql+aiomysql://user:pass@localhost/db
      #   PgSQL: postgresql+asyncpg://user:pass@localhost/db
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - uv-cache:/root/.cache/uv
    restart: unless-stopped

volumes:
  uv-cache:
